
### Login to get Token
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "admin@esntes.com",
    "password": "<PASSWORD>"
}

### Get Admin Communities
GET http://localhost:8000/api/admin/communities
Authorization: Bearer <TOKEN>


### Get Permissions
GET http://localhost:8000/api/admin/permissions
Authorization: Bearer <TOKEN>